apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: sample
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 10
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: dockersamples/static-site
        env:
        - name: AUTHOR
          value: app1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
            memory: 5Mi
          limits:
            cpu: 25m
            memory: 5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: appsvc1
  namespace: sample
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1